FROM pytorch/pytorch:2.5.1-cuda12.1-cudnn9-devel
# If you are in Chinese mainland, you may want to use the following mirror instead
# FROM docker.1ms.run/pytorch/pytorch:2.5.1-cuda12.1-cudnn9-devel

RUN apt-get update && apt-get install -y git

RUN git clone https://github.com/dtc111111/UniPR-3D.git

WORKDIR /UniPR-3D

RUN pip install -U xformers==0.0.28.post3 --index-url https://download.pytorch.org/whl/cu121

RUN pip install \
    # -i https://pypi.tuna.tsinghua.edu.cn/simple
    faiss-gpu-cu12==1.8.0.5 \
    huggingface-hub==0.25.2 \
    iopath==0.1.10 \
    loralib==0.1.2 \
    opencv-python-headless==4.10.0.84 \
    pandas==2.2.3 \
    prettytable==3.11.0 \
    pyproj==3.6.1 \
    pytorch-metric-learning==2.6.0 \
    lightning==2.6.0 \
    redis==5.1.1 \
    scikit-learn==1.5.2 \
    scipy==1.14.1


    # annotated-types==0.7.0 \
    # contourpy==1.3.0 \
    # cycler==0.12.1 \
    # einops==0.8.0 \
    # fonttools==4.54.1 \
    # gitdb==4.0.11 \
    # GitPython==3.1.43 \
    # h5py==3.12.1 \
    # kiwisolver==1.4.7 \
    # lightning-utilities==0.11.7 \
    # matplotlib==3.9.2 \
    # opencv-python==4.10.0.84 \
    # protobuf==5.28.2 \
    # py3_wget==0.1.0 \
    # pydantic==2.9.2 \
    # pydantic_core==2.23.4 \
    # pyparsing==3.1.4 \
    # regex==2024.9.11 \
    # safetensors==0.4.5 \
    # sentry-sdk==2.16.0 \
    # smmap==5.0.1 \
    # tensorboardX==2.6.2.2 \
    # termcolor==2.4.0 \
    # timm==1.0.9 \
    # tokenizers==0.19.1 \
    # transformers==4.45.2 \
    # typing-inspection==0.9.0 \
    # utm==0.7.0 \
    # wandb==0.18.3 \